version: '3.8'
services:
  php: &default-php
    build: &default-php-build
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/src
      - ./data:/var/www/data
      - ./tests:/var/www/tests
      - ./build:/var/www/build
      - ./phpunit.xml.dist:/var/www/phpunit.xml.dist
  php-8.1:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 8.1-cli
  php-8.0:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 8.0-cli
  php-7.4:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 7.4-cli
  php-7.3:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 7.3-cli
  php-7.2:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 7.2-cli
  php-7.1:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 7.1-cli
  php-7.0:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 7.0-cli
  php-5.6:
    <<: *default-php
    build:
      <<: *default-php-build
      args:
        version: 5.6-cli
